---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cribl
spec:
  template:
    spec:
      containers:
        - name: logstream-master
          resources:
            limits:
            requests:
