apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  name: {{ template "influxdb.fullname" . }}-apply-templates
  annotations:
    "helm.sh/hook-weight": "5"
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  activeDeadlineSeconds: 90
  template:
    metadata:
      annotations:
        appscope.dev/disable: "true"
      labels:
        {{- include "influxdb.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "influxdb.fullname" . }}-apply-templates
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        env:
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "influxdb.fullname" . }}-auth
                key: admin-password
          - name: INFLUXDB_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "influxdb.fullname" . }}-auth
                key: admin-token
        command:
          - bash
        args:
          - -c
          - |
            for url in {{- range .Values.templates }} {{. | quote }}{{- end}}; do \
            influx apply --force true -f $url \
            --host http://{{ template "influxdb.fullname" . }}:{{ .Values.service.port }} \
            -o {{ .Values.adminUser.organization }} \
            -t ${INFLUXDB_TOKEN}; \
            done
      restartPolicy: OnFailure
