# Default values for logstream-workergroup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

criblImage:
  repository: cribl/cribl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: "cribl-w2"

config: 
  host: cribl-internal
  group: aws
  token: criblmaster


podAnnotations: {}

env: 
  CRIBL_BEFORE_START_CMD_1: apt update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python python-pip 
  SCOPE_TAG_service: cribl-aws-wg


service:
  type: ClusterIP
  annotations: {}

  ports:
  - name: tcpjson
    port: 10001
    protocol: TCP
  - name: scope
    port: 10090
    protocol: TCP
  - name: s2s
    port: 9997
    protocol: TCP
  - name: s2s-alt
    port: 9999
    protocol: TCP
  - name: http
    port: 10080
    protocol: TCP
  - name: https
    port: 10081
    protocol: TCP    
  - name: syslog
    port: 5140
    protocol: TCP
  - name: metrics
    port: 8125
    protocol: TCP
  - name: metrics-udp
    port: 8125
    protocol: UDP

resources: 
  limits:
    cpu: 2000m
    memory: 4096Mi
  requests:
    cpu: 1250m
    memory: 512Mi


autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80

