# Default values for logstream-workergroup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

criblImage:
  repository: cribl/cribl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: "cribl-w0"

config: 
  host: cribl-internal
  group: dc1-logs
  token: criblmaster


podAnnotations: {}

env: 
  CRIBL_BEFORE_START_CMD_1: apt update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python python-pip 

service:
  type: ClusterIP
  annotations: {}

  ports:
  - name: tcpjson
    port: 10001
    protocol: TCP
  - name: s2s
    port: 9997
    protocol: TCP
  - name: s2s-alt
    port: 9999
    protocol: TCP
  - name: http
    port: 10080
    protocol: TCP
  - name: splunkhec
    port: 10088
    protocol: TCP
  - name: https
    port: 10081
    protocol: TCP    
  - name: appscope
    port: 10090
    protocol: TCP    
  - name: syslog
    port: 5140
    protocol: TCP
  # - name: metrics
  #   port: 8125
  #   protocol: TCP
  - name: elastic
    port: 10200
    protocol: TCP

resources: 
  limits:
    cpu: 4000m
    memory: 4096Mi
  requests:
    cpu: 2500m
    memory: 512Mi


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80

