---
apiVersion: v1
kind: Service
metadata:
  name: influxdb2-internal
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
  selector: 
    app.kubernetes.io/instance: influxdb2
    app.kubernetes.io/name: influxdb2
