apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb2-fix-dbrp
  annotations:
    "helm.sh/hook-weight": "2"
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  activeDeadlineSeconds: 240
  template:
    metadata:
      annotations:
        appscope.dev/disable: "true"
    spec:
      containers:
      - name: influxdb2-fix-dbrp
        image: influxdb:2.0.6-alpine
        env:
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-admin
                key: adminpass
          - name: INFLUXDB_TOKEN
            valueFrom:
              secretKeyRef:
                name: influxdb2-auth
                key: admin-token
        command:
          - bash
        args:
          - -cx
          - |
            sleep 20; 
            INF_ID=$(influx bucket ls -t ${INFLUXDB_TOKEN} --host http://influxdb2-internal:8086 --org cribl --name cribl --json | grep '"id"' | awk -F\" '{print $4}')
            [ -z "$INF_ID" ] && exit 255
            echo "INF_ID: $INF_ID"
            influx v1 dbrp create --bucket-id $INF_ID  --db cribl --default --org cribl --rp forever --host http://influxdb2-internal:8086  -t ${INFLUXDB_TOKEN} || sleep 20 
      restartPolicy: OnFailure
