---
apiVersion: batch/v1
kind: Job
metadata:
  name: gogen-datacollection-syslog
  labels:
    app.kubernetes.io/name: gogen-datacollection-syslog
spec:
  activeDeadlineSeconds: 900
  template:
    metadata:
      annotations:
        appscope.dev/disable: "true"
      labels:
        app.kubernetes.io/name: gogen-datacollection-syslog
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: datacollection-syslog
        configMap:
          name: datacollection-syslog

      containers:
        - env:
          - name: SCOPE_TAG_service
            value: gogen-datacollection-syslog
          - name: GOGEN_OUT
            value: tcp
          - name: GOGEN_URL
            value: cribl-sa:5140
          - name: GOGEN_OUTPUTTEMPLATE
            value: rfc5424
          - name: GOGEN_CONFIG_DIR
            value: /etc/gogen
          - name: GOGEN_ADDTIME
            value: "true"
          - name: GOGEN_LOGJSON
            value: "true"
          - name: GOGEN_INFO
            value: "true"
          command:
          - bash
          - -c
          - |
            set -x
            mkdir /etc/gogen
            cd /etc/gogen
            if [ -f /var/tmp/gogen-config/gogen.tgz ]; then
              tar zxf /var/tmp/gogen-config/gogen.tgz
            fi
            gogen gen
            kill 1
          image: clintsharp/gogen:latest
          volumeMounts:
          - name: datacollection-syslog
            mountPath: /var/tmp/gogen-config
          name: gogen-datacollection-syslog
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 250m
              memory: 128Mi
