apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gogen
    io.kompose.service: gogen
  name: gogen
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gogen
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: gogen
        app.kubernetes.io/name: gogen
      annotations:
        appscope.dev/disable: "true"
    spec:
      volumes:
      - name: bigjson-webhook
        configMap:
          name: bigjson-webhook
      - name: businessevent-hec
        configMap:
          name: businessevent-hec
      - name: flowlogs-syslog
        configMap:
          name: flowlogs-syslog
      - name: metrics-dogstatsd
        configMap:
          name: metrics-dogstatsd
      - name: pantraffic-syslog
        configMap:
          name: pantraffic-syslog
      - name: statechange-syslog
        configMap:
          name: statechange-syslog
      containers:
      - env:
        - name: SCOPE_TAG_service
          value: gogen-bigjson-webhook
        - name: GOGEN_OUT
          value: "http"
        - name: GOGEN_OUTPUTTEMPLATE
          value: "json"
        - name: GOGEN_URL
          value: "http://cribl-w0:10080/cribl/_bulk"
        - name: GOGEN_CONFIG_DIR
          value: "/etc/gogen"
        - name: GOGEN_ADDTIME
          value: "true"
        - name: GOGEN_LOGJSON
          value: "true"
        - name: GOGEN_INFO
          value: "true"
        image: clintsharp/gogen:latest
        volumeMounts:
        - name: bigjson-webhook
          mountPath: /var/tmp/gogen-config
        name: gogen-bigjson-webhook
        command:
        - bash
        - -c
        - |
          set -ex
          mkdir /etc/gogen
          cd /etc/gogen
          if [ -f /var/tmp/gogen-config/gogen.tgz ]; then
            tar zxf /var/tmp/gogen-config/gogen.tgz
            ls -alR /etc/gogen
          fi
          /sbin/entrypoint.sh start
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      - env:
          - name: SCOPE_TAG_service
            value: gogen-businessevent-hec
          - name: GOGEN_OUT
            value: http
          - name: GOGEN_OUTPUTTEMPLATE
            value: splunkhec
          - name: GOGEN_URL
            value: http://cribl-w0:10088/services/collector/event
          - name: GOGEN_CONFIG_DIR 
            value: /etc/gogen
          - name: GOGEN_ADDTIME
            value: "true"
          - name: GOGEN_LOGJSON
            value: "true"
          - name: GOGEN_INFO
            value: "true"
        image: clintsharp/gogen:latest
        volumeMounts:
        - name: businessevent-hec
          mountPath: /var/tmp/gogen-config
        name: gogen-businessevent-hec
        command:
        - bash
        - -c
        - |
          set -ex
          mkdir /etc/gogen
          cd /etc/gogen
          if [ -f /var/tmp/gogen-config/gogen.tgz ]; then
            tar zxf /var/tmp/gogen-config/gogen.tgz
          fi
          /sbin/entrypoint.sh start
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      - env:
          - name: SCOPE_TAG_service
            value: gogen-metrics-dogstatsd
          - name: GOGEN_OUT
            value: tcp
          - name: GOGEN_URL
            value: cribl-w1:8125
          - name: GOGEN_CONFIG_DIR
            value: /etc/gogen
          - name: GOGEN_ADDTIME
            value: "true"
          - name: GOGEN_LOGJSON
            value: "true"
          - name: GOGEN_INFO
            value: "true"
        image: clintsharp/gogen:latest
        volumeMounts:
        - name: metrics-dogstatsd
          mountPath: /var/tmp/gogen-config
        name: gogen-metrics-dogstatsd
        command:
        - bash
        - -c
        - |
          set -ex
          mkdir /etc/gogen
          cd /etc/gogen
          if [ -f /var/tmp/gogen-config/gogen.tgz ]; then
            tar zxf /var/tmp/gogen-config/gogen.tgz
          fi
          /sbin/entrypoint.sh start
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      - env:
          - name: SCOPE_TAG_service
            value: gogen-pantraffic-syslog
          - name: GOGEN_OUT
            value: tcp
          - name: GOGEN_OUTPUTTEMPLATE
            value: rfc5424
          - name: GOGEN_URL
            value: cribl-w0:5140
          - name: GOGEN_CONFIG_DIR
            value: /etc/gogen
          - name: GOGEN_ADDTIME
            value: "true"
          - name: GOGEN_LOGJSON
            value: "true"
          - name: GOGEN_INFO
            value: "true"
        image: clintsharp/gogen:latest
        volumeMounts:
        - name: pantraffic-syslog
          mountPath: /var/tmp/gogen-config
        name: gogen-pantraffic-syslog
        command:
        - bash
        - -c
        - |
          set -ex
          mkdir /etc/gogen
          cd /etc/gogen
          if [ -f /var/tmp/gogen-config/gogen.tgz ]; then
            tar zxf /var/tmp/gogen-config/gogen.tgz
          fi
          /sbin/entrypoint.sh start
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      - env:
          - name: SCOPE_TAG_service
            value: gogen-statechange-syslog
          - name: GOGEN_OUT
            value: tcp
          - name: GOGEN_OUTPUTTEMPLATE
            value: rfc5424
          - name: GOGEN_URL
            value: cribl-w0:5140
          - name: GOGEN_CONFIG_DIR
            value: /etc/gogen
          - name: GOGEN_ADDTIME
            value: "true"
          - name: GOGEN_LOGJSON
            value: "true"
          - name: GOGEN_INFO
            value: "true"
        image: clintsharp/gogen:latest
        volumeMounts:
        - name: statechange-syslog
          mountPath: /var/tmp/gogen-config
        name: gogen-statechange-syslog
        command:
        - bash
        - -c
        - |
          set -ex
          mkdir /etc/gogen
          cd /etc/gogen
          if [ -f /var/tmp/gogen-config/gogen.tgz ]; then
            tar zxf /var/tmp/gogen-config/gogen.tgz
          fi
          /sbin/entrypoint.sh start
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      - env:
          - name: SCOPE_TAG_service
            value: gogen-accesscombined-forwarder
          - name: SPLUNK_CMD
            value: cmd mkdir -p /var/log/httpd
          - name: SPLUNK_CMD_1
            value: cmd gogen -v -cd /etc/gogen -o file --filename /var/log/httpd/access_log -lj gen -s shoppingapache 2>/var/log/gogen.log &
          - name: SPLUNK_CMD_2
            value: add monitor /var/log/httpd/access_log -auth admin:cribldemo -sourcetype access_combined -index cribl
          - name: SPLUNK_CMD_3
            value: add forward-server cribl-w0:9999 -auth admin:cribldemo -ssl-cert-path /opt/splunk/etc/auth/client.pem
        image: gogen-accesscombined-forwarder
        name: gogen-accesscombined-forwarder
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      - env:
          - name: SCOPE_TAG_service
            value: gogen-authfailed-filebeat
          - name: GOGEN_OUT
            value: file
        image: gogen-authfailed-filebeat
        name: gogen-authfailed-filebeat
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      - env:
          - name: SCOPE_TAG_service
            value: gogen-flowlogs-syslog
          - name: GOGEN_OUT
            value: tcp
          - name: GOGEN_OUTPUTTEMPLATE
            value: rfc5424
          - name: GOGEN_URL
            value: cribl-w2:5140
          - name: GOGEN_CONFIG_DIR
            value: /etc/gogen
          - name: GOGEN_ADDTIME
            value: "true"
          - name: GOGEN_LOGJSON
            value: "true"
          - name: GOGEN_INFO
            value: "true"
        image: clintsharp/gogen:latest
        volumeMounts:
        - name: flowlogs-syslog
          mountPath: /var/tmp/gogen-config
        name: gogen-flowlogs-syslog
        command:
        - bash
        - -c
        - |
          set -ex
          mkdir /etc/gogen
          cd /etc/gogen
          if [ -f /var/tmp/gogen-config/gogen.tgz ]; then
            tar zxf /var/tmp/gogen-config/gogen.tgz
          fi
          /sbin/entrypoint.sh start
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      restartPolicy: Always
status: {}

