---
apiVersion: batch/v1
kind: Job
metadata:
  name: ls-deploy-job
spec:
  ttlSecondsAfterFinished: 100
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: ls-deploy-job
      annotations:
        "appscope.dev/disable": "true"
    spec:
      restartPolicy: OnFailure
      containers:
      - image: cribl/cribl:next
        command:
        - bash
        - -c
        - |
          set -x
          mkdir /tmp/clone
          cd /tmp/clone
          git clone https://github.com/criblio/cribl-demo.git
          cd cribl-demo
          git checkout $(cat /etc/demo-config/branch)
          git pull
          cd deploy-job
          CRIBL_VOLUME_DIR=/opt/cribl/config-volume CRIBL_URL=http://cribl:9000 CRIBL_ADMIN_PASSWORD=$(cat /etc/demo-config/admin.pass) ./api-script.sh
        imagePullPolicy: Always
        name: ls-deploy-job
        volumeMounts:
        - name: demo-config
          mountPath: /etc/demo-config
      volumes:
      - name: demo-config
        configMap:
          name: demo-config
